#!/bin/bash
#
# Renders the Reference section of docs/preview/website (the Starlight
# docs site) from this repo's own sources, so
# those pages cannot drift from what they describe:
#
#   agents.mdx      agents/*.md frontmatter (name, description, model, tools)
#   skills.mdx      skills/*/SKILL.md frontmatter (name, description)
#   scripts.mdx     header comments of scripts/*.sh (not *-selftest.sh) and
#                   scripts/*.py, plus providers/*/*/*.sh headers grouped
#                   by provider directory
#   hooks.mdx       hooks/*.sh headers (not selftests), plus the hooks
#                   table from .claude-plugin/plugin.json
#   config.mdx      templates/night-watchman.config.toml, fenced verbatim
#   ethos-seed.mdx  templates/ethos.md, verbatim
#   evidence.mdx    docs/evidence.md, verbatim, plus docs/cost.md, verbatim
#   faq.mdx         docs/faq.md, verbatim
#   index.mdx       a generated list of the pages above
#
# Every page starts with Starlight frontmatter (title, description) and a
# first body line marking it GENERATED — do not hand-edit any file this
# script writes; edit the source it was rendered from instead.
#
# Never touches a network or a host: every source is a file committed in this
# repo, and the only write path is the reference/ directory (or --out DIR).
#
# Usage:
#   gen-reference-docs.sh [--check] [--out DIR] [--root DIR]
#   gen-reference-docs.sh --help
#
# --check     render to a scratch directory and diff against the committed
#             pages instead of writing. Exit 0 on a clean match, 1 with a
#             unified diff on drift, 2 if the pages could not be rendered at
#             all. The 1-vs-2 split tells "docs are stale" from "repo broken".
# --out DIR   write pages to DIR instead of the real destination. For tests;
#             --check compares against DIR when --out is given.
# --root DIR  read sources from DIR instead of this repo's own root. For
#             tests only (a fixture tree shaped like this repo).
#
# Frontmatter is parsed with awk/sed only — no python, no yq.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=lib/kit.sh
. "$HERE/lib/kit.sh"

need awk sed jq diff mktemp

ROOT="$(cd "$HERE/.." && pwd)"
OUT=""
CHECK=0

while [ $# -gt 0 ]; do
    case "$1" in
        --check) CHECK=1; shift ;;
        --out)
            [ $# -ge 2 ] || die "--out requires a DIR argument"
            OUT="$2"; shift 2 ;;
        --root)
            [ $# -ge 2 ] || die "--root requires a DIR argument"
            ROOT="$2"; shift 2 ;;
        -h|--help) show_help ;;
        *) die "unknown argument: $1 (see --help)" ;;
    esac
done

DEST="${OUT:-$ROOT/docs/preview/website/src/content/docs/reference}"

GENERATED_MARK='{/* GENERATED by scripts/gen-reference-docs.sh — do not hand-edit */}'
PAGE_NAMES="agents skills scripts hooks config ethos-seed evidence faq index"


# blank VALUE — VALUE, or "-" if VALUE is empty. Guards a table cell from
# silently shifting the ones after it.
blank() { [ -n "$1" ] && printf '%s' "$1" || printf '%s' "-"; }

# mdx_escape — reads prose on stdin and backslash-escapes a bare '<' or '{'
# so MDX does not read it as a JSX tag or expression. Fenced code blocks and
# inline code spans are left untouched: MDX already renders them literally,
# and escaping there would inject a visible backslash.
mdx_escape() {
    awk '
        /^```/ { infence = !infence; print; next }
        infence { print; next }
        {
            n = split($0, parts, "`")
            out = ""
            for (i = 1; i <= n; i++) {
                seg = parts[i]
                if (i % 2 == 1) {
                    gsub(/</, "\\<", seg)
                    gsub(/\{/, "\\{", seg)
                }
                out = out seg
                if (i < n) out = out "`"
            }
            print out
        }
    '
}

# frontmatter TITLE DESCRIPTION — Starlight frontmatter plus the GENERATED
# marker line that opens every page's body.
frontmatter() {
    printf -- '---\ntitle: %s\ndescription: %s\n---\n' "$1" "$2"
    printf '%s\n\n' "$GENERATED_MARK"
}

# fm_field FILE FIELD — print FIELD's value from FILE's frontmatter. Prints
# nothing and returns 1 if the field is absent; the caller decides if that
# is fatal (this project's die-inside-a-subshell rule).
fm_field() {
    awk -v field="$2" '
        NR == 1 && $0 == "---" { next }
        $0 == "---" { exit }
        {
            prefix = field ":"
            if (substr($0, 1, length(prefix)) == prefix) {
                val = substr($0, length(prefix) + 1)
                sub(/^[ \t]+/, "", val)
                print val
                found = 1
                exit
            }
        }
        END { exit (found ? 0 : 1) }
    ' "$1"
}

# header_body FILE — the leading '#'-comment header, shebang skipped and
# '# ' stripped, so paragraph boundaries survive; for a .py file, the leading
# triple-quoted docstring instead.
header_body() {
    case "$1" in
        *.py)
            awk '
                NR == 1 && /^#!/ { next }
                /^"""/ && c == 0 {
                    c = 1
                    line = $0
                    sub(/^"""/, "", line)
                    if (line != "") print line
                    next
                }
                /^"""/ && c == 1 { exit }
                c == 1 { print; next }
            ' "$1"
            ;;
        *)
            awk '
                NR == 1 && /^#!/ { next }
                /^#/ { line = $0; sub(/^# ?/, "", line); print line; next }
                { exit }
            ' "$1"
            ;;
    esac
}

# first_paragraph — reads a header body on stdin, prints the lines up to
# (not including) the first blank line.
first_paragraph() {
    awk '
        /^[[:space:]]*$/ { if (started) exit; next }
        { print; started = 1 }
    '
}

# usage_block — reads a header body on stdin, prints a "Usage:" line and
# every line after it up to (not including) the next blank line. Prints
# nothing if no such line exists.
usage_block() {
    awk '
        grab && /^[[:space:]]*$/ { exit }
        grab { print; next }
        /^Usage:/ { grab = 1; print }
    '
}

# script_section FILE LABEL — one "### LABEL" section: first paragraph of
# the header, then its Usage: block (if any) in a fenced code block.
script_section() {
    local f="$1" label="$2" body summary usage
    body="$(header_body "$f")"
    summary="$(printf '%s\n' "$body" | first_paragraph | mdx_escape)"
    usage="$(printf '%s\n' "$body" | usage_block)"
    printf '### %s\n\n' "$label"
    printf '%s\n\n' "$summary"
    if [ -n "$usage" ]; then
        # shellcheck disable=SC2016  # literal backticks for a fenced code block, not command substitution
        printf '```text\n%s\n```\n\n' "$usage"
    fi
}


render_agents() {
    frontmatter "Agents" "Generated from every agents/*.md frontmatter block (name, description, model, tools)."
    [ -d "$ROOT/agents" ] || die "no such directory: $ROOT/agents"
    local f name description model tools
    while IFS= read -r f; do
        name="$(fm_field "$f" name)" || die "gen-reference-docs.sh: $f: missing 'name' in frontmatter"
        description="$(fm_field "$f" description)" || die "gen-reference-docs.sh: $f: missing 'description' in frontmatter"
        description="$(printf '%s\n' "$description" | mdx_escape)"
        model="$(fm_field "$f" model)" || model=""
        tools="$(fm_field "$f" tools)" || tools=""
        printf '## %s\n\n' "$name"
        printf '%s\n\n' "$description"
        [ -n "$model" ] && printf -- '- **Model:** %s\n' "$model"
        [ -n "$tools" ] && printf -- '- **Tools:** %s\n' "$tools"
        printf '\n'
    done < <(find "$ROOT/agents" -maxdepth 1 -type f -name '*.md' | sort)
}

render_skills() {
    frontmatter "Skills" "Generated from every skills/*/SKILL.md frontmatter block (name, description)."
    [ -d "$ROOT/skills" ] || die "no such directory: $ROOT/skills"
    local f name description
    while IFS= read -r f; do
        name="$(fm_field "$f" name)" || die "gen-reference-docs.sh: $f: missing 'name' in frontmatter"
        description="$(fm_field "$f" description)" || die "gen-reference-docs.sh: $f: missing 'description' in frontmatter"
        description="$(printf '%s\n' "$description" | mdx_escape)"
        printf '## %s\n\n' "$name"
        printf '%s\n\n' "$description"
    done < <(find "$ROOT/skills" -mindepth 2 -maxdepth 2 -type f -name 'SKILL.md' | sort)
}

render_scripts() {
    frontmatter "Scripts" "Generated from every scripts/*.sh (excluding selftests) and scripts/*.py header, plus provider script headers grouped by provider directory."
    [ -d "$ROOT/scripts" ] || die "no such directory: $ROOT/scripts"

    printf '## Top-level scripts\n\n'
    local f rel
    while IFS= read -r f; do
        rel="${f#"$ROOT"/}"
        script_section "$f" "$rel"
    done < <(find "$ROOT/scripts" -maxdepth 1 -type f \( -name '*.sh' -o -name '*.py' \) ! -name '*-selftest.sh' | sort)

    if [ -d "$ROOT/providers" ]; then
        local group last_group=""
        while IFS= read -r f; do
            rel="${f#"$ROOT"/providers/}"
            group="$(dirname "$rel")"
            if [ "$group" != "$last_group" ]; then
                printf '## Provider: %s\n\n' "$group"
                last_group="$group"
            fi
            script_section "$f" "providers/$rel"
        done < <(find "$ROOT/providers" -mindepth 3 -maxdepth 3 -type f -name '*.sh' \
            ! -name '*-selftest.sh' ! -name 'selftest.sh' | sort)
    fi
}

render_hooks() {
    frontmatter "Hooks" "Generated from every hooks/*.sh header (excluding selftests), plus the hooks table in .claude-plugin/plugin.json."
    [ -d "$ROOT/hooks" ] || die "no such directory: $ROOT/hooks"

    printf '## Hook scripts\n\n'
    local f rel
    while IFS= read -r f; do
        rel="hooks/$(basename "$f")"
        script_section "$f" "$rel"
    done < <(find "$ROOT/hooks" -maxdepth 1 -type f -name '*.sh' ! -name '*-selftest.sh' | sort)

    local plugin_json="$ROOT/.claude-plugin/plugin.json"
    [ -f "$plugin_json" ] || die "no such file: $plugin_json"
    printf '## Registered hooks (.claude-plugin/plugin.json)\n\n'
    printf '| Event | Matcher | Command | Timeout |\n'
    printf '| --- | --- | --- | --- |\n'
    local event matcher command timeout hooks_tsv
    # Captured into a variable so jq's exit status is checked: a `while read`
    # never sees it, so a malformed plugin.json would exit 0 with an empty table.
    hooks_tsv="$(jq -r '
        .hooks | to_entries[] as $ev
        | $ev.value[] as $grp
        | $grp.hooks[]
        | [$ev.key, ($grp.matcher // "-"), .command, (.timeout | tostring)]
        | @tsv
    ' "$plugin_json")" || die "gen-reference-docs.sh: jq failed to parse $plugin_json"
    if [ -n "$hooks_tsv" ]; then
        while IFS="$(printf '\t')" read -r event matcher command timeout; do
            # shellcheck disable=SC2016  # literal backticks around the command cell, not command substitution
            printf '| %s | %s | `%s` | %s |\n' "$(blank "$event")" "$(blank "$matcher")" "$(blank "$command")" "$(blank "$timeout")"
        done < <(printf '%s\n' "$hooks_tsv")
    fi
    printf '\n'
}

render_config() {
    frontmatter "Config" "Generated from templates/night-watchman.config.toml, rendered as a fenced toml block with the file's own comments intact."
    local toml="$ROOT/templates/night-watchman.config.toml"
    [ -f "$toml" ] || die "no such file: $toml"
    printf '```toml\n'
    cat "$toml"
    printf '```\n'
}

render_ethos_seed() {
    frontmatter "Ethos seed" "Generated from templates/ethos.md, reproduced verbatim."
    local ethos="$ROOT/templates/ethos.md"
    [ -f "$ethos" ] || die "no such file: $ethos"
    mdx_escape < "$ethos"
}

render_evidence() {
    frontmatter "Evidence" "Generated from docs/evidence.md and docs/cost.md, both reproduced verbatim."
    local evidence="$ROOT/docs/evidence.md" cost="$ROOT/docs/cost.md"
    [ -f "$evidence" ] || die "no such file: $evidence"
    [ -f "$cost" ] || die "no such file: $cost"
    mdx_escape < "$evidence"
    printf '\n'
    mdx_escape < "$cost"
}

render_faq() {
    frontmatter "FAQ" "Generated from docs/faq.md, reproduced verbatim."
    local faq="$ROOT/docs/faq.md"
    [ -f "$faq" ] || die "no such file: $faq"
    mdx_escape < "$faq"
}

render_index() {
    frontmatter "Reference" "Generated index of the Reference section — agents, skills, scripts, hooks, config, ethos seed, evidence, and the FAQ, each rendered from this repo's own sources so these pages cannot drift from them."
    printf -- '- [Agents](/reference/agents/) — agent frontmatter (name, description, model, tools).\n'
    printf -- '- [Skills](/reference/skills/) — skill frontmatter (name, description).\n'
    printf -- '- [Scripts](/reference/scripts/) — script header comments and Usage blocks.\n'
    printf -- '- [Hooks](/reference/hooks/) — hook header comments and the registered-hooks table.\n'
    printf -- '- [Config](/reference/config/) — the config.toml template.\n'
    printf -- '- [Ethos seed](/reference/ethos-seed/) — the ethos.md template.\n'
    printf -- '- [Evidence](/reference/evidence/) — the README'"'"'s evidence section and the cost ledger doc.\n'
    printf -- '- [FAQ](/reference/faq/) — what this is, and why it is neither a workflow nor an agent team.\n'
}

render_page() {
    case "$1" in
        agents) render_agents ;;
        skills) render_skills ;;
        scripts) render_scripts ;;
        hooks) render_hooks ;;
        config) render_config ;;
        ethos-seed) render_ethos_seed ;;
        evidence) render_evidence ;;
        faq) render_faq ;;
        index) render_index ;;
        *) die "unknown page: $1" ;;
    esac
}

# generate_all OUTDIR — render every page into OUTDIR. Renders to a scratch
# directory first and touches OUTDIR only once every page has succeeded, so a
# mid-render failure leaves OUTDIR's existing contents untouched.
generate_all() {
    local outdir="$1" scratch p
    scratch="$(mktemp -d "${TMPDIR:-/tmp}/gen-reference-docs.render.XXXXXX")" || die "cannot create scratch directory"
    # Not registered for cleanup at all: generate_all can be called more
    # than once, and each failure path below removes its own scratch dir.
    # shellcheck disable=SC2086  # PAGE_NAMES is a deliberate space-separated list, no special chars
    for p in $PAGE_NAMES; do
        if ! render_page "$p" > "$scratch/$p.mdx"; then
            rm -rf "$scratch"
            die "failed to render $p.mdx"
        fi
    done
    if ! mkdir -p "$outdir"; then
        rm -rf "$scratch"
        die "cannot create output directory: $outdir"
    fi
    # shellcheck disable=SC2086  # PAGE_NAMES is a deliberate space-separated list, no special chars
    for p in $PAGE_NAMES; do
        if ! mv "$scratch/$p.mdx" "$outdir/$p.mdx"; then
            rm -rf "$scratch"
            die "cannot write $outdir/$p.mdx"
        fi
    done
    rm -rf "$scratch"
}


if [ "$CHECK" -eq 1 ]; then
    SCRATCH="$(mktemp -d "${TMPDIR:-/tmp}/gen-reference-docs.XXXXXX")" || die "cannot create scratch directory"
    # shellcheck disable=SC2329  # called indirectly via kit_on_exit
    clean_scratch() { rm -rf "$SCRATCH"; }
    kit_on_exit clean_scratch

    # A subshell so ANY failure here becomes "could not evaluate" (exit 2),
    # distinct from a drift finding (exit 1). kit.sh's die() always exits 1;
    # the remap happens only at this --check boundary.
    if ! ( [ -d "$ROOT" ] || die "no such root directory: $ROOT"; generate_all "$SCRATCH" ) 2>"$SCRATCH.err"; then
        echo "gen-reference-docs.sh --check: could not render pages to evaluate drift:" >&2
        cat "$SCRATCH.err" >&2
        rm -f "$SCRATCH.err"
        exit 2
    fi
    rm -f "$SCRATCH.err"

    if [ -d "$DEST" ] && diff -ru "$DEST" "$SCRATCH" >"$SCRATCH.diff" 2>&1; then
        rm -f "$SCRATCH.diff"
        exit 0
    fi
    if [ ! -d "$DEST" ]; then
        echo "gen-reference-docs.sh --check: $DEST does not exist yet" >&2
        diff -ru /dev/null "$SCRATCH" 2>&1 || true
        exit 1
    fi
    echo "gen-reference-docs.sh --check: reference pages have drifted from their sources:" >&2
    cat "$SCRATCH.diff" >&2
    rm -f "$SCRATCH.diff"
    exit 1
fi

[ -d "$ROOT" ] || die "no such root directory: $ROOT"
generate_all "$DEST"
echo "gen-reference-docs.sh: wrote $(echo "$PAGE_NAMES" | wc -w | tr -d ' ') pages to $DEST"
