#!/bin/bash
#
# Selftest for gen-reference-docs.sh. Runs entirely against the fixture
# trees under scripts/fixtures/gen-reference-docs/ — repo/ (two fake
# agents, one skill, one .sh and one .py script with a Usage block, plus
# *-selftest.sh/selftest.sh exclusions, one provider script, one hook, a
# mini plugin.json, config toml, ethos.md, and README.md/docs/cost.md),
# bad-agent/ (a frontmatter missing 'description'), and bad-plugin-json/
# (a copy of repo/ with an unparsable plugin.json). Nothing here reads or
# writes anything outside this worktree's scratch directories.
#
# What is asserted:
#   1  each generated page under a scratch --out directory matches its
#      checked-in expected/ file byte-for-byte, including the MDX-safe
#      {/* GENERATED */} marker, mdx_escape's bare-'<'/'{' escaping (and
#      its inline-`backtick`-span exemption), and the .py docstring-header
#      extraction path
#   2  --check exits 0 when the fixture's own committed reference/ pages
#      (copied in from expected/) match what the generator would produce
#   3  --check exits 1, with non-empty diff output, once one of those
#      committed pages is hand-edited (the negative case)
#   4  a frontmatter missing 'description' dies (exit 1) with a message
#      naming the field, instead of writing a page with a blank field
#   5  that same failure, mid-render, leaves a pre-existing --out
#      directory's other contents untouched (the staged-write fix — a
#      page is never written truncated next to what was already there)
#   6  --check tells "could not evaluate" (exit 2) apart from "drift"
#      (exit 1): the same bad-agent fixture, via --check, exits 2
#   7  a malformed plugin.json dies (exit 1, not a silent exit-0
#      header-only table) because jq's own exit status is now checked
#
# Usage: scripts/gen-reference-docs-selftest.sh [path-to-gen-reference-docs.sh]
# Defaults to the sibling scripts/gen-reference-docs.sh.

set -euo pipefail

# pipe_ok — no-op. Documents a pipeline whose non-zero exit means "found
# nothing to list" rather than a real failure — the assertion right after
# it is what explains an empty result either way.
pipe_ok() { return 0; }

HERE="$(cd "$(dirname "$0")" && pwd)"
GEN="${1:-$HERE/gen-reference-docs.sh}"
[ -x "$GEN" ] || { echo "cannot execute $GEN" >&2; exit 2; }

FIXTURES="$HERE/fixtures/gen-reference-docs"
REPO_SRC="$FIXTURES/repo"
EXPECTED="$FIXTURES/expected"
[ -d "$REPO_SRC" ] || { echo "cannot find fixture repo: $REPO_SRC" >&2; exit 2; }
[ -d "$EXPECTED" ] || { echo "cannot find expected/ fixture: $EXPECTED" >&2; exit 2; }

PASS=0
FAIL=0
ok()  { echo "ok - $1"; PASS=$((PASS + 1)); }
bad() { echo "FAIL - $1"; FAIL=$((FAIL + 1)); }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# A scratch copy of the fixture repo — the negative --check case edits a
# "committed" page in place, so the checked-in fixture must never be
# touched directly.
REPO="$WORK/repo"
cp -R "$REPO_SRC" "$REPO"
chmod +x "$REPO"/scripts/*.sh "$REPO"/providers/tracker/fake/*.sh "$REPO"/hooks/*.sh

REF_DEST="$REPO/docs/preview/website/src/content/docs/reference"

# ---- test 1: --out renders every page, matching expected/ byte-for-byte.
OUT="$WORK/out"
if "$GEN" --root "$REPO" --out "$OUT" >"$WORK/gen.out" 2>"$WORK/gen.err"; then
    ok "generator exits 0 against the fixture tree"
else
    bad "generator should exit 0 against the fixture tree (see $WORK/gen.err)"
fi

# ---- test 1a: the GENERATED marker is an MDX expression comment, never
# a raw HTML comment (MDX rejects "<!-- -->" in prose — see
# scripts.mdx's own header for the incident this fixes).
if grep -q '^{/\* GENERATED by scripts/gen-reference-docs.sh' "$OUT/agents.mdx" \
    && ! grep -q '<!--' "$OUT"/*.mdx; then
    ok "GENERATED marker is an MDX-safe {/* ... */} comment, no raw <!-- --> anywhere"
else
    bad "GENERATED marker should be {/* ... */}, and no page should contain a raw <!-- HTML comment -->"
fi

# ---- test 1b: a bare '<' / '{' in prose (agent-two's description, and
# fake-script.sh's summary) is backslash-escaped so MDX cannot mistake it
# for JSX/an expression; the SAME sequence inside the Usage: fenced code
# block is left alone, since fenced content is already rendered literally.
if grep -q '\\<path>, e\.g\. PROJECT-\\{id},' "$OUT/agents.mdx"; then
    ok "a bare '<'/'{' in an agent description is escaped for MDX"
else
    bad "agent-two's description should read as an escaped ...\\\\<path>... PROJECT-\\\\{id}. in $OUT/agents.mdx"
fi
if grep -q 'PROJECT-\\<numeric id>' "$OUT/scripts.mdx" && grep -q '  fake-script.sh <arg>$' "$OUT/scripts.mdx"; then
    ok "a script summary's '<'/'{' is escaped, but its fenced Usage: block is left verbatim"
else
    bad "scripts.mdx should escape the summary's PROJECT-<numeric id> while leaving 'fake-script.sh <arg>' verbatim inside its fence"
fi
# shellcheck disable=SC2016  # literal backticks in a -F (fixed-string) grep pattern, not command substitution
if grep -qF '`<since>` flag that must stay unescaped' "$OUT/agents.mdx"; then
    ok "a '<'/'{' inside an inline \`single-backtick\` code span is left unescaped"
else
    bad "agents.mdx should leave agent-two's backticked \`<since>\` unescaped (only bare '<'/'{' outside code spans get escaped)"
fi

# ---- test 1c: the scripts/*.py docstring-header path is exercised (no
# shell '#' header at all — a distinct extraction path from every other
# fixture script).
if grep -q '### scripts/fake-script.py' "$OUT/scripts.mdx" \
    && grep -q 'a tiny fixture Python script with a docstring header' "$OUT/scripts.mdx"; then
    ok "a .py script's docstring header is extracted into scripts.mdx"
else
    bad "scripts.mdx should contain a ### scripts/fake-script.py section from its docstring header"
fi

for name in agents skills scripts hooks config ethos-seed evidence index; do
    if [ ! -f "$OUT/$name.mdx" ]; then
        bad "$name.mdx was not generated"
    elif diff -u "$EXPECTED/$name.mdx" "$OUT/$name.mdx" >"$WORK/$name.diff" 2>&1; then
        ok "$name.mdx matches expected/$name.mdx"
    else
        bad "$name.mdx differs from expected/$name.mdx:"
        cat "$WORK/$name.diff" >&2
    fi
done

# ---- test 2: --check exits 0 once the fixture's own reference/ pages are
# populated from expected/ (the "committed" state matches the sources).
mkdir -p "$REF_DEST"
cp "$EXPECTED"/*.mdx "$REF_DEST"/
if "$GEN" --root "$REPO" --check >"$WORK/check1.out" 2>"$WORK/check1.err"; then
    ok "--check exits 0 when committed pages match their sources"
else
    bad "--check should exit 0 on a clean match (see $WORK/check1.err)"
fi

# ---- test 3 (negative case): hand-edit a committed page, --check must
# now exit 1 and print a non-empty diff. This is the check's own
# oracle-independence proof — a check that can only ever pass has not
# been tested (see docs/testing-philosophy.md).
printf '\nHAND-EDITED, SHOULD BE DETECTED AS DRIFT\n' >>"$REF_DEST/agents.mdx"
set +e
"$GEN" --root "$REPO" --check >"$WORK/check2.out" 2>"$WORK/check2.err"
CHECK2_STATUS=$?
set -e
if [ "$CHECK2_STATUS" -eq 1 ]; then
    ok "--check exits 1 once a committed page is hand-edited"
else
    bad "--check should exit 1 on drift, got exit $CHECK2_STATUS"
fi
if grep -q "HAND-EDITED" "$WORK/check2.err"; then
    ok "--check's diff output names the drifted line"
else
    bad "--check's diff output should mention the hand-edited line (see $WORK/check2.err)"
fi

# ---- test 4: an agent missing 'description' in its frontmatter dies
# loudly with a specific message (fm_field's fallible-return-then-die
# path), instead of silently writing a page with a blank description.
BAD_AGENT="$FIXTURES/bad-agent"
[ -d "$BAD_AGENT" ] || { echo "cannot find fixture: $BAD_AGENT" >&2; exit 2; }
set +e
"$GEN" --root "$BAD_AGENT" --out "$WORK/badagent-out" >"$WORK/badagent.out" 2>"$WORK/badagent.err"
BADAGENT_STATUS=$?
set -e
if [ "$BADAGENT_STATUS" -eq 1 ]; then
    ok "a missing 'description' in an agent's frontmatter dies with exit 1"
else
    bad "missing 'description' should die with exit 1, got exit $BADAGENT_STATUS"
fi
if grep -q "missing 'description' in frontmatter" "$WORK/badagent.err"; then
    ok "the missing-description die message names the field"
else
    bad "expected a \"missing 'description' in frontmatter\" message (see $WORK/badagent.err)"
fi

# ---- test 5: that same failure, mid-render, must leave a pre-existing
# --out directory's OTHER contents untouched — no truncated/partial page
# ever lands next to what was already there (the staged-write fix).
STAGED="$WORK/staged-dest"
mkdir -p "$STAGED"
echo "keep me" >"$STAGED/KEEP.txt"
set +e
"$GEN" --root "$BAD_AGENT" --out "$STAGED" >/dev/null 2>"$WORK/staged.err"
set -e
# shellcheck disable=SC2038  # filenames here are fixture-controlled (KEEP.txt, *.mdx), never adversarial
STAGED_LISTING="$(find "$STAGED" -maxdepth 1 -type f | xargs -n1 basename | tr '\n' ' ')" || pipe_ok
if [ "$STAGED_LISTING" = "KEEP.txt " ]; then
    ok "a failed render leaves a pre-existing --out directory untouched (no partial pages written)"
else
    bad "a failed render should leave \$STAGED containing only KEEP.txt, got: $STAGED_LISTING"
fi

# ---- test 6: --check distinguishes "could not evaluate" (exit 2) from
# actual drift (exit 1) — the same bad-agent fixture, this time via
# --check, must exit 2, not 1.
set +e
"$GEN" --root "$BAD_AGENT" --check >"$WORK/badagent-check.out" 2>"$WORK/badagent-check.err"
BADAGENT_CHECK_STATUS=$?
set -e
if [ "$BADAGENT_CHECK_STATUS" -eq 2 ]; then
    ok "--check exits 2 (not 1) when its sources can't even be rendered to evaluate drift"
else
    bad "--check should exit 2 on a could-not-evaluate precondition, got exit $BADAGENT_CHECK_STATUS"
fi

# ---- test 7: a malformed .claude-plugin/plugin.json is caught by jq's
# own exit status, not silently swallowed by a `jq | while read` pipeline
# that never observes it (the checked-jq fix).
BAD_PLUGIN_JSON="$FIXTURES/bad-plugin-json"
[ -d "$BAD_PLUGIN_JSON" ] || { echo "cannot find fixture: $BAD_PLUGIN_JSON" >&2; exit 2; }
set +e
"$GEN" --root "$BAD_PLUGIN_JSON" --out "$WORK/badplugin-out" >"$WORK/badplugin.out" 2>"$WORK/badplugin.err"
BADPLUGIN_STATUS=$?
set -e
if [ "$BADPLUGIN_STATUS" -eq 1 ]; then
    ok "a malformed plugin.json dies with exit 1 instead of a silent header-only table"
else
    bad "a malformed plugin.json should die with exit 1, got exit $BADPLUGIN_STATUS"
fi
if grep -q "jq failed to parse" "$WORK/badplugin.err"; then
    ok "the malformed-plugin.json die message names the jq failure"
else
    bad "expected a \"jq failed to parse\" message (see $WORK/badplugin.err)"
fi

echo
echo "$PASS passed, $FAIL failed"
if [ "$FAIL" -ne 0 ]; then
    echo "gen-reference-docs-selftest.sh: FAILED"
    exit 1
fi
echo "gen-reference-docs-selftest.sh: all assertions passed"
exit 0
